words = {
    0: "zéro",
    1: "un",
    2: "deux",
    3: "trois",
    4: "quatre",
    5: "cinq",
    6: "six",
    7: "sept",
    8: "huit",
    9: "neuf",
    10: "dix",
    11: "onze",
    12: "douze",
    13: "treize",
    14: "quatorze",
    15: "quinze",
    16: "seize",
    20: "vingt",
    30: "trente",
    40: "quarante",
    50: "cinquante",
    60: "soixante",
    70: "septante",
    80: "quatre-vingts",
    90: "nonante",
    100: "cent",
}

magnitude_words = {
    0: "",
    1: "mille",
    2: "million",
    3: "milliard",
    4: "billion",
    5: "billiard",
    6: "trillion",
    7: "trilliard",
    8: "quadrillion",
    9: "quadrilliard",
    10: "quintillion",
    11: "quintilliard",
    12: "sextillion",
    13: "sextilliard",
    14: "septillion",
    15: "septilliard",
    16: "octillion",
    17: "octilliard",
    18: "nonillion",
    19: "nonilliard",
    20: "décillion",
    21: "décilliard",
}